name: DISCVR Build
author: Ben Bimber
description: Build the DISCVR modules
branding:
  icon: 'git-branch'
  color: 'black'
inputs:
  github_token:
    description: GitHub token secret
    required: true
  artifactory_user:
    description: LabKey Artifactory User
    required: false
  artifactory_password:
    description: LabKey Artifactory Password
    required: false  
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    BASE_BRANCH: ${{ inputs.github.base_ref }}
    GITHUB_EVENT_NAME: ${{ inputs.github.event_name }}
    ARTIFACTORY_USER: ${{ inputs.artifactory_user }}
    ARTIFACTORY_PASSWORD: ${{ inputs.artifactory_password }}    
