name: Build Docker for Shiny
on:
  workflow_dispatch:
  #schedule:
  #  - cron:  "0 3 * * *"
jobs:
  generate:
    name: Build Docker
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/bimberlabinternal/devops
          tag-sha: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Shiny/Dockerfile
          pull: true
          push: true
          tags: ghcr.io/bimberlabinternal/shiny:latest
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.title=shiny
            org.opencontainers.image.description=This builds a container running R Shiny, with GeneSetViz and HISTA


