name: Build Docker for Paragraph
on:
  workflow_dispatch:

jobs:
  generate:
    name: Build Paragraph Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/bimberlabinternal/paragraph
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0
        with:
          # Use the previous version of buildx to force docker to save a V1 image,
          # since Exacloud's outdated docker version cannot handle V2/OCI:
          version: v0.9.1

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5.3.0
        with:
          file: ./containers/paragraph/Dockerfile
          context: ./containers/paragraph
          pull: true
          push: true
          tags: ghcr.io/bimberlabinternal/paragraph:latest
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.title=paragraph
            org.opencontainers.image.description=This builds a container to run paragraph
